Management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentification.urls')),
    path('', include('infrastructure.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infrastructure/urls.py
from django.urls import path
from . import views



urlpatterns = [
   path('', views.homepage, name='homepage'), 
   path('personnel/', views.personnel, name='personnel'),
   path('administration_infra', views.administration, name='administration'),
   path('utilisateur', views.Utilisateur.as_view(), name="liste_utilisateurs"),
   path('create_user', views.create_user, name='create_user'),
   path('machine_create/', views.machine_create, name='machine_create'),
   path('machine_update/<int:machine_id>/', views.machine_update, name='modifier_machine'),
   path('machine_detail/<int:machine_id>/', views.machine_detail, name='machine_detail'),
   path('machine_delete/<int:machine_id>/', views.machine_delete, name='supprimer_machine')
]

infrastructure/models.py
from django.db import models

from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

from django.contrib.auth import get_user_model

User = get_user_model()
    
    

class Infrastructure(models.Model):
    nom = models.CharField(max_length=100)  # Nom de l'infrastructure
    responsable = models.OneToOneField(User, on_delete=models.CASCADE, related_name='respo')  # Responsable de l'infrastructure (relation OneToOne avec le modèle User)

    def __str__(self):
        return self.nom

class Machine(models.Model):
    STATUS_CHOICES = (
        ('defaillant', 'Défaillance'),
        ('bien_portant', 'Fonctionnel'),
        ('en_maintenance', 'En maintenance'),
    )

    TYPE_MACHINE_CHOICES = (
        ('pc_windows', 'PC Windows'),
        ('pc_linux', 'PC Linux'),
        ('desktop_windows', 'Ordinateur de bureau Windows'),
        ('desktop_linux', 'Ordinateur de bureau Linux'),
        ('routeur', 'Routeur'),
        ('serveur', 'Serveur'),
        ('unite_centrale', 'Unité centrale'),
    )

    nom = models.CharField(max_length=100)  # Nom de la machine
    proprietaire = models.ForeignKey(User, on_delete=models.CASCADE, related_name='machines_proprietaire', null=True)  # Propriétaire de la machine (relation OneToOne avec le modèle User)
    infrastructure = models.ForeignKey(Infrastructure, on_delete=models.CASCADE)  # Infrastructure à laquelle la machine appartient (relation ForeignKey avec le modèle Infrastructure)
    date_maintenance = models.DateTimeField(null=True, blank=True)  # Date de la dernière maintenance de la machine (peut être nulle ou vide)
    date_de_creation = models.DateTimeField(auto_now_add=True)
    date_derniere_modification = models.DateTimeField(auto_now_add=True)
    statut = models.CharField(max_length=15, choices=STATUS_CHOICES, default='bien_portant')  # Statut de la machine
    type = models.CharField(max_length=15, choices=TYPE_MACHINE_CHOICES, default='pc_windows')  # type de la machine
    image = models.ImageField(upload_to='machine_images/', blank=True, null=True)  # Image de la machine
    caracteristiques = models.TextField(blank=True, null=True)  # Caractéristiques de la machine
    est_assignee = models.BooleanField(default=True)  # Indique si la machine est assignée ou non à cet utilisateur
    modifie_par = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.nom
    
    def get_image_url(self):
        if self.image:
            return self.image.url 
        return 


class Update(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)  # Machine concernée par la mise à jour (relation ForeignKey avec le modèle Machine)
    modifie_par = models.ForeignKey(User, on_delete=models.CASCADE, related_name='upates_users')  # Utilisateur ayant effectué la mise à jour (relation ForeignKey avec le modèle User)
    date_modification = models.DateTimeField(auto_now_add=True)  # Date de la mise à jour (définie automatiquement lors de la création de l'objet)

    def __str__(self):
        return f"Mise a jour de {self.machine.nom} par {self.modifie_par} a {self.date_modification}"




@receiver(post_save, sender=Machine)
def create_machine_update(sender, instance, created, **kwargs):
    """
    Crée une nouvelle entrée dans la table Update lorsque la machine est modifiée.
    """
    if not created:
        Update.objects.create(
            machine=instance,
            modifie_par=instance.modifie_par,
            date_modification=timezone.now()
        )


infrastructure/forms.py
from django import forms
from .models import Infrastructure, Machine
from django.contrib.auth.models import User
 
class MachineForm(forms.ModelForm):
    class Meta:
        model = Machine
        exclude = ['infrastructure', 'modifie_par', 'date_de_creation', 'date_derniere_modification']
        widgets = {
            'nom': forms.TextInput(attrs={'class': 'form-control'}),
            'proprietaire': forms.Select(attrs={'class': 'form-control'}),
            'date_maintenance': forms.DateInput(attrs={'class': 'form-control'}),
            'statut': forms.Select(attrs={'class': 'form-control'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
            'caracteristiques': forms.Textarea(attrs={'class': 'form-control'}),
            
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }


class UserForm(forms.ModelForm):
    machine = forms.ModelChoiceField(required=False, queryset=Machine.objects.filter(est_assignee=False), widget=forms.Select(attrs={'class': 'form-control'}))

    
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name', 'machine']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }

infrastructure/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Infrastructure, Machine
from .forms import MachineForm, UserForm
from django.contrib import messages
from django.views import View

from django.contrib.auth import get_user_model

User = get_user_model()

from django.contrib.auth.hashers import make_password
from .forms import UserForm

def create_user(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            password = request.POST.get('password')
            hashed_password = make_password(password)
            user.password = hashed_password
            machine_id = request.POST.get('machine')
            user.save()
            if machine_id:
                machine = Machine.objects.get(id=machine_id)
                machine.proprietaire = user
                machine.est_assignee = True
                machine.save()
            
            messages.success(request, "Utilisateur créé avec succès")
            return redirect('administration')
    else:
        user_form = UserForm()
    return render(request, 'create_user.html', {'form': user_form})

def homepage(request):
    """ page d'acceuil """
    return render(request, 'home.html')

@login_required 
def personnel(request):
    machines = Machine.objects.filter(proprietaire=request.user)
    admin = False
    if machines:
        machine = machines.first()
        return render(request, 'personel.html', {"machine": machine, 'admin': admin})
    return render(request, 'personel.html', {'admin': admin})


@login_required 
def administration(request):
    user = request.user
    infras= Infrastructure.objects.filter(responsable=user)
    admin=True
    if infras:
        infra = infras.first()
        machines = Machine.objects.filter(infrastructure=infra)    
        return render(request, 'administration.html', {'machines': machines, 'admin': admin})
    return render(request, 'administration.html', {'admin': admin})


class Utilisateur(LoginRequiredMixin, View):
    template_name = 'infrastructure/liste_users.html'
    
    def get(self, request):
        user = request.user
        infras= Infrastructure.objects.filter(responsable=user)
        if infras:
            infra = infras.first()
            machines = Machine.objects.filter(infrastructure=infra)
            personnels = User.objects.filter(id__in=[machine.proprietaire.id for machine in machines])
            return render(request, self.template_name, {'personnels':personnels})
        return render(request, self.template_name)



@login_required
def machine_create(request):
    """
    Permet à l'utilisateur connecté de créer une nouvelle machine
    """
    user = request.user
    
    infrastructure =  Infrastructure.objects.filter(responsable=user)
    
    if infrastructure:
    
        
        infrastructure = infrastructure.first()

        if request.method == 'POST':
            form = MachineForm(request.POST, request.FILES)
            if form.is_valid():
                machine = form.save(commit=False)
                machine.infrastructure = infrastructure
                machine.save()
                messages.success(request, 'Machine creee avec success.')
                return redirect('administration')
        else:
            form = MachineForm()

        context = {
            'form': form,
        }
    else:
        messages.error(request, "Vous n'avez pas la permission d'effectuer cette d'action.")    
        

    return render(request, 'infrastructure/machine_create.html', context)

@login_required
def machine_update(request, machine_id):
    """
    Permet à l'utilisateur connecté de mettre à jour une machine existante
    """
    user = request.user
    infrastructure = Infrastructure.objects.filter(responsable=user).first()

    if infrastructure:
        machine = Machine.objects.get(id=machine_id)

        if request.method == 'POST':
            form = MachineForm(request.POST, request.FILES, instance=machine)
            if form.is_valid():
                machine = form.save(commit=False)
                machine.modifie_par = user  # Ajout du champ "modified_by"
                machine.save()
                return redirect('administration')
        else:
            form = MachineForm(instance=machine)

        context = {
            'form': form,
        }
    else:
        messages.error(request, "Vous n'avez pas la permission d'effectuer cette action.")
        return redirect('dashboard')

    return render(request, 'infrastructure/machine_update.html', context)


@login_required
def machine_delete(request, machine_id):
    """
    Permet à l'utilisateur connecté de supprimer une machine existante
    """
    machine = Machine.objects.get(id=machine_id)
    if machine.infrastructure.responsable == request.user:
        machine.delete()
        messages.success(request, f"{machine.name} a ete supprimee avec success ")
    else:
        messages.error(request, "Vous n'avez pas la permission d'effectuer cette action. ")    
    return redirect('dashboard')

@login_required
def machine_detail(request, machine_id):
    machine = Machine.objects.get(id=machine_id)
    return render(request, 'infrastructure/machine_detail.html', {'machine':machine})

templates/infrastructure/liste_users.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    

    <div class="col-12">
        <h2>Liste des personnels de l'infrastructure</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nom</th>
          <th>Prénom</th>
          <th>Email</th>
          <th>Date de création</th>
          <th>Date de dernière connexion</th>
        </tr>
      </thead>
      <tbody>
        {% for personnel in personnels %}
          <tr>
            <td>{{ personnel.last_name }}</td>
            <td>{{ personnel.first_name }}</td>
            <td>{{ personnel.email }}</td>
            <td>{{ personnel.date_joined }}</td>
            <td>{{ personnel.last_login }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
    </div>
  </div>
{% endblock %}

templates/infrastructure/machine_create.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center text-capitalize">Ajouter une machine</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Ajouter</button>
    </form>
{% endblock %}

templates/infrastructure/machine_detail.html
{% extends 'base.html' %}


{% block content %}

<div class="row">
    <li class="list-group-item">
        <div class="row">
          <div class="col-md-7">
            <h3>{{ machine.nom }}</h3>
            <table class="table">
              <tbody>
                <tr>
                  <th scope="row">Propriétaire</th>
                  <td>{{ machine.proprietaire.first_name }} {{ machine.proprietaire.last_name }}</td>
                </tr>
                <tr>
                  <th scope="row">Infrastructure</th>
                  <td>{{ machine.infrastructure.nom }}</td>
                </tr>
                <tr>
                  <th scope="row">Date de maintenance</th>
                  <td>{{ machine.date_maintenance }}</td>
                </tr>
                <tr>
                  <th scope="row">Date de création</th>
                  <td>{{ machine.date_de_creation }}</td>
                </tr>
                <tr>
                  <th scope="row">Date de dernière modification</th>
                  <td>{{ machine.date_derniere_modification }}</td>
                </tr>
                <tr>
                  <th scope="row">Statut</th>
                  <td>{{ machine.get_statut_display }}</td>
                </tr>
                <tr>
                  <th scope="row">Type</th>
                  <td>{{ machine.get_type_display }}</td>
                </tr>
                <tr>
                  <th scope="row">Caractéristiques</th>
                  <td>{{ machine.caracteristiques }}</td>
                </tr>
                <tr>
                  <th scope="row">Est assignée</th>
                  <td>{{ machine.est_assignee }}</td>
                </tr>
                <tr>
                  <th scope="row">Dernière modification par</th>
                  <td>{{ machine.modifie_par.username }}</td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="col-md-4">
            <img src="{{ machine.get_image_url }}" alt="Image de la machine" class="img-fluid">
          </div>
        </div>
        
    </li>
   
      <div> 

        <a href="{% url 'supprimer_machine' machine.id %}" class="btn btn-danger">Supprimer</a>
        <a href="{% url 'modifier_machine' machine.id %}" class="btn btn-primary">Modifier</a>
      </div>
{% endblock %}

templates/infrastructure/machine_update.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center text-capitalize">Modifier une machine</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    </form>
{% endblock %}